networks:
  app-network:
    driver: bridge #if external, external: true

services:
  receiver-frontend:
    build:
      context: ./receiver-frontend
      dockerfile: Dockerfile
    container_name: receiver-frontend
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - RECEIVER_SERVICE_EVENTS_URL=http://receiver-service:3001/api/events
    depends_on:
      - receiver-service
    networks:
      - app-network

  receiver-service:
    build:
      context: ./receiver-service
      dockerfile: Dockerfile
    container_name: receiver-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - ALLOW_ORIGIN=http://receiver-frontend:3002
    networks:
      - app-network

  webhook_service:
    build:
      context: ./webhook_service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - WEBHOOK_URL=http://receiver-service:3001/api/webhook
    networks:
      - app-network